name: EDA
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py37h06a4308_0
  - cudatoolkit=11.0.3=h15472ef_8
  - freetype=2.10.4=h0708190_1
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h7f8727e_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.19.1=h4ff587b_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtiff=4.0.10=hc3755c2_1005
  - libuv=1.40.0=h7b6447c_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h5e8e339_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h219a48f_0
  - ncurses=6.3=h7f8727e_2
  - ninja=1.10.2=h4bd325d_0
  - numpy=1.21.5=py37he7a7128_2
  - numpy-base=1.21.5=py37hf524024_2
  - olefile=0.46=pyh9f0ad1d_1
  - openssl=1.1.1s=h7f8727e_0
  - pip=21.2.2=py37h06a4308_0
  - python=3.7.11=h12debd9_0
  - python_abi=3.7=2_cp37m
  - pytorch=1.7.0=py3.7_cuda11.0.221_cudnn8.0.3_0
  - readline=8.1.2=h7f8727e_1
  - setuptools=58.0.4=py37h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.38.0=hc218d9a_0
  - tabulate=0.8.10=py37h06a4308_0
  - tensorboardx=2.2=pyhd3eb1b0_0
  - tk=8.6.11=h1ccaba5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7f8727e_4
  - zstd=1.4.9=ha95c52a_0
  - pip:
    - absl-py==1.0.0
    - backcall==0.2.0
    - blis==0.7.9
    - cached-property==1.5.2
    - cachetools==5.0.0
    - catalogue==2.0.8
    - charset-normalizer==2.0.12
    - click==8.0.4
    - confection==0.0.4
    - cycler==0.11.0
    - cymem==2.0.7
    - dataclasses==0.6
    - decorator==5.1.1
    - docker-pycreds==0.4.0
    - easydict==1.9
    - filelock==3.6.0
    - fonttools==4.31.2
    - future==0.18.2
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-auth==2.6.2
    - google-auth-oauthlib==0.4.6
    - grpcio==1.44.0
    - h5py==3.6.0
    - huggingface-hub==0.4.0
    - idna==3.3
    - importlib-metadata==4.11.3
    - ipdb==0.13.9
    - ipython==7.32.0
    - jedi==0.18.1
    - jinja2==3.1.2
    - joblib==1.1.0
    - kiwisolver==1.4.0
    - langcodes==3.3.0
    - markdown==3.3.6
    - markupsafe==2.1.2
    - matplotlib==3.5.1
    - matplotlib-inline==0.1.3
    - mccabe==0.7.0
    - murmurhash==1.0.9
    - oauthlib==3.2.0
    - packaging==21.3
    - pandas==1.3.5
    - parso==0.8.3
    - pathtools==0.1.2
    - pathy==0.10.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.0.1
    - plyfile==0.7.4
    - preshed==3.0.8
    - promise==2.3
    - prompt-toolkit==3.0.28
    - protobuf==3.19.4
    - psutil==5.9.0
    - ptyprocess==0.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.8.0
    - pydantic==1.8.2
    - pydocstyle==6.1.1
    - pyflakes==2.4.0
    - pygments==2.11.2
    - pylama==8.3.8
    - pyparsing==3.0.7
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pyyaml==6.0
    - regex==2022.3.15
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - sacremoses==0.0.49
    - scipy==1.7.3
    - sentencepiece==0.1.96
    - sentry-sdk==1.5.8
    - setproctitle==1.2.2
    - shortuuid==1.0.8
    - smart-open==6.3.0
    - smmap==5.0.0
    - snowballstemmer==2.2.0
    - srsly==2.4.5
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - termcolor==1.1.0
    - thinc==8.0.17
    - tokenizers==0.11.6
    - toml==0.10.2
    - torchaudio==0.7.0
    - torchvision==0.8.0
    - tqdm==4.63.1
    - traitlets==5.1.1
    - transformers==4.17.0
    - trimesh==3.10.5
    - typer==0.4.2
    - typing-extensions==4.1.1
    - urllib3==1.26.9
    - wandb==0.12.11
    - wasabi==0.10.1
    - wcwidth==0.2.5
    - werkzeug==2.1.0
    - yaspin==2.1.0
    - zipp==3.7.0
prefix: /opt/conda/envs/EDA
